### ISSUE TITLE
Can't find gtest-config in ubuntu 16.04 TLS

### ISSUE THREAD

**Issue by lixiaoquan** [oracle/ktf#2]
I tried two ways to build and install gtest, but still can't find gtest-config
1)
```bash
apt-get install libgtest-dev
then build source from /usr/src/gtest
```
2)
```bash
git clone https://github.com/google/googletest
cd googltest
cmake ..
make 
sudo make install
```

**Comment by knuto** [comment]
Hi, thanks for the interest in KTF. I am aware of this issue: gtest-config is in the source still, but not installed, instead a cleaner approach using pkgconfig has been added to googletest.
I have a version that seems to work, also with an additional fix, for Ubuntu, which has a slightly different 
build of the linker. I'll push those changes soon - just need to do some more testing first.

**Comment by knuto** [comment]
You would probably want to use the github version of googletest though, as the released version
likely does not yet contain the pkgconfig stuff. For the record: I have tested that forthcoming KTF version with 718fd88d8f145c63b8cc134cf8fed92743cc112f of googletest on Ubuntu.

**Comment by janijuvan** [comment]
Wow what are the odds, I also ran into this issue just now.
Trying to run towards an older 1.7.0 gtest in the mean while, but I get undefined reference errors for stuff that are in libgtest. Guess I am better off waiting a few more days.

**Comment by knuto** [comment]
Yes, the old gtest had a number of issues related to parameterized tests, which is used by KTF to expand the kernel tests. We had to operate with a few patches on gtest to make it work, but they are no longer needed with the new version.

**Comment by knuto** [comment]
The current version now should hopefully configure and build smoothly against the latest googletest git repo. Let me know if you see additional issues!
