### ISSUE TITLE
Broken build with latest googletest

### ISSUE THREAD

**Issue by evdenis** [oracle/ktf#23]
Instruction https://github.com/oracle/ktf/blob/master/doc/installation.rst suggest to use latest googletest framework as an option.

> cd ~/src
> git clone https://github.com/google/googletest.git

This doesn't work and results in compilation error:
```
ktf_run.cpp: In static member function ‘static int ktf::Kernel::AddToRegistry()’:
ktf_run.cpp:124:44: error: no matching function for call to ‘testing::internal::ParameterizedTestSuiteInfo<ktf::Kernel>::AddTestPattern(const char*, const char [1], testing::internal::TestMetaFactory<ktf::Kernel>*&)’
  124 |     tci->AddTestPattern(it->c_str(), "", mf);
      |                                            ^
In file included from .../googletest/install/include/gtest/gtest-param-test.h:178,
                 from .../googletest/install/include/gtest/gtest.h:67,
                 from ktf.h:12,
                 from ktf_int.h:18,
                 from ktf_run.cpp:12:
.../googletest/install/include/gtest/internal/gtest-param-util.h:522:8: note: candidate: ‘void testing::internal::ParameterizedTestSuiteInfo<TestSuite>::AddTestPattern(const char*, const char*, testing::internal::TestMetaFactoryBase<typename TestSuite::ParamType>*, testing::internal::CodeLocation) [with TestSuite = ktf::Kernel; typename TestSuite::ParamType = std::__cxx11::basic_string<char>]’
  522 |   void AddTestPattern(const char* test_suite_name, const char* test_base_name,
      |        ^~~~~~~~~~~~~~
.../googletest/install/include/gtest/internal/gtest-param-util.h:522:8: note:   candidate expects 4 arguments, 3 provided
```

Actually, the build also fails on latest gtest release (1.10.0).

**Comment by knuto** [comment]
Hi, thanks for the information. I have built KTF successfully with the latest googletest release for Fedora, which seems to be based off 1.10.0 - package info says:

Source RPM  : gtest-1.10.0-3.fc33.src.rpm
Build Date  : Tue 28 Jul 2020 10:22:00 PM CEST

It does however seem to have been made some changes to that function in the (unreleased) commit 5e0cf72b7cd)
which as far as I can observe is some 210 commits beyond the release-1.10.0 tag and that seems to fail to build for me as well.

**Comment by knuto** [comment]
I have (sigh) created an autoconf compile test to detect the change as there is no version info 
I can use to conditionally compile on. I will push this to knuto/ktf soon.

**Comment by evdenis** [comment]
> Actually, the build also fails on latest gtest release (1.10.0).
> I have built KTF successfully with the latest googletest release for Fedora, which seems to be based off 1.10.0

It failed for me on Gentoo 1.10.0_p20200702 package version. Seems like it's based on a commit behind 1.10.0 tag.

> I have (sigh) created an autoconf compile test to detect the change as there is no version info

Thanks!
