### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by aiden00** [oracle/ktf#3]
Hi, I have just tried to run the examples with no luck. I am on ubuntu 16.04(4.13.0). I built everything fine with gtest, then after building I ran insmod ktf.ko, insmod hello.ko then user/ktfrun. The binary runs, however it detect no tests and gtest out displays "Running 0 tests from 0 test cases". 
Is there something I am missing?
Thanks.

**Comment by knuto** [comment]
There seems to be an issue with the way the linker works on Ubuntu - I haven't really been able to find a solution I am entirely happy with for this yet.
- KTF works by executing a query to the kernel as a side effect of static variable initialization inside libktf. No symbols from libktf is used by the ktfrun application. What appears to happen is that the library does not get linked at all (whether static or dynamic). On Oracle Linux/Fedora/Redhat the initialization happens as intended.

 I have tried various linker options to ktfrun, making symbols undefined to enforce the linking, creating an init function for the library, but so far without any luck. The only way seems to be to reference something inside libktf from main, which is not as transparent as I wanted it to be.

**Comment by cheinger** [comment]
Hi, would you be able to post the temporary fix in the comments here? I am really eager to use this framework on Ubuntu.

**Comment by knuto** [comment]
With the latest commits I am able to build and run the selftests on Ubuntu without issues.
