### ISSUE TITLE
Does this project support mock function feature?

### ISSUE THREAD

**Issue by ekeroc** [oracle/ktf#7]
Hi, I would like to check does this project support mock function feature?

And the project still maintenance or update now? 
Thanks.

**Comment by ekeroc** [comment]
Okay, thanks for your answer.

And the mock feature might such as [gmock](https://github.com/google/googlemock/tree/master/googlemock) or [cmock](https://github.com/ThrowTheSwitch/CMock), then we can use the mock or stub function in kernel unit test

**Comment by ekeroc** [comment]
Or already could use gmock usage in ktf now?

**Comment by alan-maguire** [comment]
On 24/07/18 03:10, ekeroc wrote:
>
> Or already could use gmock usage in ktf now?
>
I'd need to look at it a bit more since most of the examples are 
C++-centric.
Possibly some of the work described in

https://www.codeproject.com/articles/1040972/using-googletest-and-googlemock-frameworks-for-emb

might be useful for taking a C-focused approach?

**Comment by knuto** [comment]
I agree with Alan in that it might not be worthwhile to try to use gmock for deployment in the kernel, as it is very C++ oriented. Also if a 100% mock interface is generated anyway, why attempt to run it in the kernel at all, why not just compile it for and run it in user space, where it is much easier to debug? But this is maybe more something complimentary to what we try to do with KTF. I have some code exploring this area and I can say it is not trivial, but that there are definitely benefits to be made.

**Comment by ekeroc** [comment]
Due to I would like to use unit test to test my kernel code by ktf, and check if the code is no problem or not, so maybe need the mock function for unit test.

**Comment by ekeroc** [comment]
Is probably could use cmock framework in ktf ?

And could I ask a problem? How do you compile gtest library with ktf in linux kernel, that is to say, the C standard function library how to compile with kernel code? 
As far as I know that is unable to do, or is that has other skill and knowledge could share with me?
Thanks.

**Comment by knuto** [comment]
You don't compile gtest _with_ the kernel, just build it the standard way as described in the KTF documentation - for simple kernel only unit tests, ktf integrates with the reporting and test execution part of gtest, but the tests themselves execute in the kernel and just reports results back via gtest.
