### ISSUE TITLE
Compilation fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by mellowcandle** [oracle/ktf#8]
Running build exactly as instructed. build machine: Ubuntu 16.04

```
Making all in kernel
make[1]: Entering directory '/home/rfried/dev/ktf-build/kernel'
make[1]: *** No rule to make target '../ktf/kernel/Makefile.in', needed by 'Makefile'.  Stop.
make[1]: Leaving directory '/home/rfried/dev/ktf-build/kernel'
Makefile:410: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by mellowcandle** [comment]
Problem is in the included "ktf_gen.mk", something is wrong with that script.

**Comment by knuto** [comment]
It seems you have used relative paths to the source tree, which I haven't been able to make work.
Try using an absolute path instead. I'll see if I can handle that case more gracefully, or at least update the docs.

**Comment by mellowcandle** [comment]
No I didn't. attached the configuration again. it still doesn't work...

```
fried@epg-ubt28:~/dev/ktf (master) $ autoreconf
rfried@epg-ubt28:~/dev/ktf (master) $ ./configure KVER=`uname -r`
rfried@epg-ubt28:~/dev/ktf (master) $ ./configure KVER=`uname -r`
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking for stdlib.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNL3... yes
checking for GTEST... yes
checking for assert counters... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating kernel/Makefile
config.status: creating selftest/Makefile
config.status: creating examples/Makefile
config.status: creating lib/Makefile
config.status: creating user/Makefile
config.status: creating doc/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
rfried@epg-ubt28:~/dev/ktf (master) $ make
Making all in kernel
make[1]: Entering directory '/home/rfried/dev/ktf/kernel'
make[1]: *** No rule to make target 'kernel/Makefile.in', needed by 'Makefile'.  Stop.
make[1]: Leaving directory '/home/rfried/dev/ktf/kernel'
Makefile:410: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by knuto** [comment]
This is strictly speaking still a relative path, and what you try to do (to build in the source tree) is not the recommended/documented way. I really want to encourage the separate tree usage.

The idea is to use a separate build and source tree, that way you can use the same KTF and test source against multiple kernels, which is the most important reason for not just submitting KTF as a kernel patch.

**Comment by mellowcandle** [comment]
OK.
When building outside the source tree with absolute paths it's working.
this is crazy though.
BTW, my goal is to add KTF to buildroot / Open-embedded(yocto) and this way
it will never be possible.

Additionally, there's no standard way to compile Linux modules using
autotools. I think it's better to separate the two. This way you could also
send the KTF patches upstream.
What do you think ?

Thanks,
Ramon.

**Comment by knuto** [comment]
I see! Definitely an interesting use case, and maybe a good reason to fix the in-source compilation, if that's a Yocto requirement. I think I'd like to try to support both an in-kernel and an out-of-tree way, but from the same ("meta") source. I have a git tool project that aids in this, but that is not ready for prime time just yet.

For the out-of-tree way, autotools seems to be the least painful of the common standardized ways (I have experimented with Cmake as well, but there were a number of rather painful downsides).

The intent is that the generated Makefiles in the kernel module trees should be usable as "plain" kernel module makefiles, and that the additional logic to build out-of-tree is contained in the optional ktf_gen.mk file, which will only be included if it exists.

Let me see if I can fix the in-source compilation. I have it working in other, old projects that uses a similar setup, but must admit I didn't pay that much attention to it for this version of KTF, since I generally would not encourage it. But in a Yocto like setting where Yocto itself maintains the different builds, it makes sense.

**Comment by mellowcandle** [comment]
I'm not sure if in-source compilation is necessary for Yocto.
But a command line option to configure to disable automatic compilation of
the kernel module would definitely assist in builtroot which can't build
both kernel module & other target in the same Make.

**Comment by knuto** [comment]
Hmm - I have only scratched the surface of Yocto/Openembedded and do not claim to understand the details, but I would think it should be possible in principle (probably with some caveats due to corss compiling etc) - you just have to find the right kernel tree and environment to build in. The benefit would be the tests can be maintained in a single version but used against all kernels. Disabling the kernel part can be done by removing the kernel directories from the SUBDIRS variable in the top level Makefile.am, but KTF is not much without the kernel part.

**Comment by knuto** [comment]
I haven't looked at buildroot before. The challenges to support KTF in it is likely similar to a pure kernel integration, and mostly with the user land side - we'd probably have to support a different front-end than googletest, if not for other reasons, at least for the C++ side of it. Supporting multiple frontends is on the "nice to have" list, preferably use/extend what's already in use the kernel for user land unit tests, but keep gtest/googletest as an option in the out-of-tree situation.

**Comment by knuto** [comment]
The above commit fixes in-source compilation.
